### ISSUE TITLE
Reusing client connection to send messages

### ISSUE THREAD

**Issue by ltozi** [noodlefrenzy/node-amqp-1-0#42]
"node-amqp-1-0 version 0.0.6"

I initialize and store client connection at my program startup because I need to call client.send() quite often but after some minutes of  inactivity  I receive this error while performing send again:

"Cannot call method 'write' of null" (lib/connection.js - line 330)

Should I perform a connection for every send or I must set some hearthbeat?

Thanks

**Comment by noodlefrenzy** [comment]
The heartbeat should be being sent by my code, so you shouldn't need to do anything.  I'll investigate.  Are you connecting to EventHub (e.g. vs. ActiveMQ or another AMQP server)?

Also, I've done a few bug fixes since 0.0.6 - I'm on 0.0.8 now.  Might want to try a fresh npm install and see if the problem still occurs.

**Comment by ltozi** [comment]
This is the core of a workaround I made to solve the problem but it doesn't seem to work:

```
// The service is created and first connected, later some send are performed
// thisAdapter.service = new AMQPClient(AMQPClient.policies.ServiceBusQueuePolicy);

//CHECK BEFORE EVERY SEND
if ( thisAdapter.service._connection.connected == false ) {
	logger.info(prefix + "AMQP client was disconnected. Trying to reconnect");

	thisAdapter.service.connect(serviceEndpoint, function(conn_err) {
	    if (conn_err) {
		logger.error(prefix + 'Connection error for endpoint: ' + amqpsEndpoint, conn_err);
	    } else {
		logger.info(prefix + "Connection OK");

	    }

	    done(conn_err);
	});
}
```

I receive an error on reconnecting the same instance:

"The connection was inactive for more than the allowed period of time. TrackingId:dd2d628a20cc4e86a60f47c7fec98a60_G32,TimeStamp:2/6/2015 4:14:19 PM"


This means I must create another instance in order to make it work again?

**Comment by ltozi** [comment]
node-amqp-1-0 updated to 0.0.8 but problem still persist

**Comment by ltozi** [comment]
Sorry, I forgot to tell you I'm connecting to a service bus queue

**Comment by noodlefrenzy** [comment]
Ok, thanks!  I'm testing it out on EventHub right now, I'll check queues next if this works (but hopefully I'll run into the same issue you are).

**Comment by ltozi** [comment]
Great! I provide you other informations that can help you find the problem. The client instance I mentioned above is only used for sending messages. 

Instead, each listener I instantiate has a separate client instance on which receive() method is called. In this case I confirm that your hearthbeat works as expected and the error of connection timeout is disappeared.

**Comment by noodlefrenzy** [comment]
The code I'm trying against EventHub is send-only, looks like:

```
    var msgVal = 0;
    var secs = 0;
    var secsUntilSend = 10;
    var client = new AMQPClient(AMQPClient.policies.EventHubPolicy);
    client.connect(uri, function() {
        client.send({ "DataString": "From Node", "DataValue": msgVal }, sendAddr, { 'x-opt-partition-key' : 'pk'+msgVal }, function() {});
        msgVal++;
        setInterval(function () {
            ++secs;
            if (secsUntilSend === secs) {
                console.log('Sending at interval ' + secsUntilSend);
                secsUntilSend *= 2;
                secs = 0;
                client.send({ "DataString": "From Node", "DataValue": msgVal }, sendAddr, { 'x-opt-partition-key' : 'pk'+msgVal }, function() {});
                msgVal++;
            }
        }, 1000);
    });
```

So it's basically starting at a 10-sec delay and doubling until I see the problem.  So far it seems to be coping (160 secs).  Do you have any information on how long a delay you have between sends before the problem manifests?

**Comment by ltozi** [comment]
I cannot tell the exact delay. I noticed that it took about 10 minutes
since a I stopped sending messages.

Il giorno 17:54 Ven 06/Feb/2015 Michael Lanzetta <notifications@github.com>
ha scritto:

**Comment by noodlefrenzy** [comment]
Ok, works on EventHub up to 1280 seconds (at which point I stopped the test).  Testing on SB queues now.

**Comment by noodlefrenzy** [comment]
Interesting!  At about 9-10 minutes, like you were saying, the queue connection spit out the following error:

```
  amqp10-Session Processing frame DetachFrame: {"frameType":0,"channel":0,"handle":0,"closed":true,"error":{"descriptor"
:{"buffer":[0,0,0,0,0,0,0,29],"offset":0},"condition":{"contents":"amqp:link:detach-forced"},"description":"The link '47
56847:amqps://RxTx:N%2Fgb3dvpb%2B1hlFfmOp%2BoCad8hplsKxskW3lIKieE1BY%3D@milanz-hub-ns.servicebus.windows.net/milanzq2_TX
' is force detached by the broker due to errors occurred in publisher(link7620). Detach origin: AmqpMessagePublisher.Fau
lt. TrackingId:f332312c0000000300001dc454d4fb56_G18_B23,TimeStamp:2/6/2015 5:55:56 PM","errorInfo":null}} +1ms
```

I'll take a look at why this isn't getting propagated back to the client, and why I don't re-start the link when it shuts down like that.  But I'll also see if I can find a smaller test-case and send it on to the ServiceBus team.

Thanks for helping me hunt this down, and for your patience.  I'll let you know as soon as I have any additional details.

(Also, if you want to watch this error for yourself on your side, just set the environment variable DEBUG=amqp10* - but prepare for a lot of output)

**Comment by noodlefrenzy** [comment]
I've just published a new version on npm (0.0.9) that should mitigate this issue.  When it gets the DETACH frame above, it logs the error to the console, tears down the link, and then on the next send it'll re-attach.  I've verified that this works against ServiceBus queues, watching it rebuild the link after an error.  Please let me know if you still have problems, and in the meantime I'll follow up with the ServiceBus team and see if they can help me diagnose this issue further on their end.

Thanks!
Mike

**Comment by ltozi** [comment]
Hi Mike,

as you suggested, I set the DEBUG variable and it seems that the Detach problem still persist: 
![detach frame error](https://cloud.githubusercontent.com/assets/10612162/6105826/c67689b0-b05b-11e4-91b5-5ff3685d6090.png)

Anyway, now I can temporary solve the problem by recalling connect() on my service instance, as written some poste above (is this the right way ?). In this way, the client is able to send and receive message again, even if I see these logs about Disposition Frames:

amqp10-Session Processing frame DispositionFrame: {"frameType":0,"channel":0,"role":true,"first":95,"last":null,"settled":true,"state":{"descriptor":{"buffer":[0,0,0,0,0,0,0,36],"offset":0}},"batchable":null} +0ms
  amqp10-Session Not yet processing frames of type DispositionFrame +0ms

Thanks,
Luigi

**Comment by noodlefrenzy** [comment]
Have you ```npm install```ed my latest code?  In that code I've mitigated this behavior by re-attaching the link when it detaches (and watched it in action) - I'll test that mitigation again today and get back to you with any details.

As for the behavior itself, according to the ServiceBus team this is expected behavior - they drop the link, but not the connection, after a certain period of inactivity.  Note that this is _not_ true for EventHub, only for queues (and likely topics - I haven't tested them, but they're on the same backbone).

Reopening until we get this resolved.

**Comment by ltozi** [comment]
Yes, I updated to the latest version 0.0.10

**Comment by noodlefrenzy** [comment]
Hmm, this might be expected behavior - did you try and send another message _after_ it had detached?  I basically don't re-attach the link until it's demanded.

**Comment by noodlefrenzy** [comment]
I've verified it on my side - it'll detach the link, leave it detached, then reattach on the next send call.

Also, though, after ~20 minutes ServiceBus kills the connection entirely, so I've added logic to harvest all the links and re-connect when the next send/receive happens - please update to 0.0.11 and try again, and definitely try sending once the link gets detached to verify the re-attach behavior.

Thanks!  Leaving this open until I get confirmation from you that it's working.

**Comment by ltozi** [comment]
Ok now works! Thanks!
